name: carcare
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.18.0
  localstorage: ^5.0.0
  dio: ^5.2.0 
  flutter_secure_storage: ^8.0.0 
  flutter_hooks: ^0.18.0  # Check for the latest version
  provider: ^6.1.0  # Check for the latest version
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/carLogin.png
    - assets/image/skyLogin.png
    - assets/image/loginBackground.png
    - assets/image/password.png
    - assets/cars/NoCar.png
    - assets/cars/Hatchback.png
    - assets/cars/Coupe.png
    - assets/cars/Sedan.png
    - assets/cars/SUV.png
    - assets/cover.png
    - assets/fuelMeter.png
    - assets/repair.png
    - assets/customIcons/garage.png
    - assets/manWithCar.png
    - assets/whiteCar.png
    - assets/gasPic.jpg